/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UseJacoco;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
   
    public boolean NotTestedLibraryMethod() {
        return true;
    }
    
}
